{"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/61", "repository_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning", "labels_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/61/labels{/name}", "comments_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/61/comments", "events_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/61/events", "html_url": "https://github.com/PyTorchLightning/pytorch-lightning/issues/61", "id": 477938750, "node_id": "MDU6SXNzdWU0Nzc5Mzg3NTA=", "number": 61, "title": "DDP support on Jupyter Notebook", "user": {"login": "immanuelweber", "id": 1731035, "node_id": "MDQ6VXNlcjE3MzEwMzU=", "avatar_url": "https://avatars.githubusercontent.com/u/1731035?v=4", "gravatar_id": "", "url": "https://api.github.com/users/immanuelweber", "html_url": "https://github.com/immanuelweber", "followers_url": "https://api.github.com/users/immanuelweber/followers", "following_url": "https://api.github.com/users/immanuelweber/following{/other_user}", "gists_url": "https://api.github.com/users/immanuelweber/gists{/gist_id}", "starred_url": "https://api.github.com/users/immanuelweber/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/immanuelweber/subscriptions", "organizations_url": "https://api.github.com/users/immanuelweber/orgs", "repos_url": "https://api.github.com/users/immanuelweber/repos", "events_url": "https://api.github.com/users/immanuelweber/events{/privacy}", "received_events_url": "https://api.github.com/users/immanuelweber/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1297090688, "node_id": "MDU6TGFiZWwxMjk3MDkwNjg4", "url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/labels/feature", "name": "feature", "color": "a2eeef", "default": false, "description": "Is an improvement or enhancement"}, {"id": 1297090689, "node_id": "MDU6TGFiZWwxMjk3MDkwNjg5", "url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/labels/help%20wanted", "name": "help wanted", "color": "008672", "default": true, "description": "Open to be worked on"}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 23, "created_at": "2019-08-07T13:44:59Z", "updated_at": "2019-10-09T11:10:06Z", "closed_at": "2019-08-07T18:20:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm trying to get ddp, fp16 etc running, however just setting the gpus and the `distributed_backend='ddp'` lets the CoolModel demo crash on my machine. I'm running it from a jupyter notebook with python 3.6 on a Ubuntu 18.04 machine with 2xV100.\r\nThe errors directly in the notebook are:\r\n\r\n> Exception                                 Traceback (most recent call last)\r\n<ipython-input-8-3a22b74b1d8d> in <module>\r\n     69 \r\n     70 # train (1 epoch only here for demo)\r\n---> 71 trainer.fit(model)\r\n     72 \r\n     73 # view tensorflow logs\r\n\r\n> /opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/site-packages/pytorch_lightning/models/trainer.py in fit(self, model)\r\n    425                 \"\"\"\r\n    426                 warnings.warn(msg)\r\n--> 427                 mp.spawn(self.ddp_train, nprocs=len(self.data_parallel_device_ids), args=(model, ))\r\n    428 \r\n    429         # 1 gpu or dp option triggers training using DP module\r\n\r\n> /opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py in spawn(fn, args, nprocs, join, daemon)\r\n    165 \r\n    166     # Loop on join until it returns True or raises an exception.\r\n--> 167     while not spawn_context.join():\r\n    168         pass\r\n\r\n> /opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)\r\n    106                 raise Exception(\r\n    107                     \"process %d terminated with exit code %d\" %\r\n--> 108                     (error_index, exitcode)\r\n    109                 )\r\n    110 \r\n\r\n> Exception: process 0 terminated with exit code 1\r\n\r\nand in the jupyter server output window:\r\n\r\n> Traceback (most recent call last):                                                                                      \r\n  File \"<string>\", line 1, in <module>                                                                                \r\n  File \"/opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/multiprocessing/spawn.py\", line 105, in spawn_main \r\n    exitcode = _main(fd)                                                                                              \r\n  File \"/opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/multiprocessing/spawn.py\", line 115, in _main        \r\n    self = reduction.pickle.load(from_parent)                                                                           \r\nAttributeError: Can't get attribute 'CoolModel' on <module '__main__' (built-in)>  \r\n\r\nI installed apex as it is written it the repository.", "closed_by": {"login": "williamFalcon", "id": 3640001, "node_id": "MDQ6VXNlcjM2NDAwMDE=", "avatar_url": "https://avatars.githubusercontent.com/u/3640001?v=4", "gravatar_id": "", "url": "https://api.github.com/users/williamFalcon", "html_url": "https://github.com/williamFalcon", "followers_url": "https://api.github.com/users/williamFalcon/followers", "following_url": "https://api.github.com/users/williamFalcon/following{/other_user}", "gists_url": "https://api.github.com/users/williamFalcon/gists{/gist_id}", "starred_url": "https://api.github.com/users/williamFalcon/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/williamFalcon/subscriptions", "organizations_url": "https://api.github.com/users/williamFalcon/orgs", "repos_url": "https://api.github.com/users/williamFalcon/repos", "events_url": "https://api.github.com/users/williamFalcon/events{/privacy}", "received_events_url": "https://api.github.com/users/williamFalcon/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/61/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/61/timeline", "performed_via_github_app": null}