{"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/26", "repository_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning", "labels_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/26/labels{/name}", "comments_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/26/comments", "events_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/26/events", "html_url": "https://github.com/PyTorchLightning/pytorch-lightning/issues/26", "id": 474316174, "node_id": "MDU6SXNzdWU0NzQzMTYxNzQ=", "number": 26, "title": "Cannot load saved model.", "user": {"login": "lkhphuc", "id": 12573521, "node_id": "MDQ6VXNlcjEyNTczNTIx", "avatar_url": "https://avatars.githubusercontent.com/u/12573521?v=4", "gravatar_id": "", "url": "https://api.github.com/users/lkhphuc", "html_url": "https://github.com/lkhphuc", "followers_url": "https://api.github.com/users/lkhphuc/followers", "following_url": "https://api.github.com/users/lkhphuc/following{/other_user}", "gists_url": "https://api.github.com/users/lkhphuc/gists{/gist_id}", "starred_url": "https://api.github.com/users/lkhphuc/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/lkhphuc/subscriptions", "organizations_url": "https://api.github.com/users/lkhphuc/orgs", "repos_url": "https://api.github.com/users/lkhphuc/repos", "events_url": "https://api.github.com/users/lkhphuc/events{/privacy}", "received_events_url": "https://api.github.com/users/lkhphuc/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2019-07-30T00:38:56Z", "updated_at": "2019-10-21T22:28:15Z", "closed_at": "2019-07-30T03:04:13Z", "author_association": "NONE", "active_lock_reason": null, "body": "I cannot load model back after saved, using `load_from_metrics`:\r\n```\r\nTraceback (most recent call last):\r\n  File \"eval-metric.py\", line 60, in <module>\r\n    main(hyperparams)\r\n  File \"eval-metric.py\", line 32, in main\r\n    on_gpu=False, map_location=None)\r\n  File \"/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/root_module/root_module.py\", line 112, in load_from_metrics\r\n    model = cls(hparams)\r\n  File \"/home/jupyter/kaggle-CellSignal/arcface_module.py\", line 74, in __init__\r\n    super().__init__(hparams)\r\n  File \"/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/root_module/root_module.py\", line 12, in __init__\r\n    super(LightningModule, self).__init__(*args, **kwargs)\r\nTypeError: __init__() takes 1 positional argument but 2 were given\r\n```\r\nReally don't know what went wrong.", "closed_by": {"login": "lkhphuc", "id": 12573521, "node_id": "MDQ6VXNlcjEyNTczNTIx", "avatar_url": "https://avatars.githubusercontent.com/u/12573521?v=4", "gravatar_id": "", "url": "https://api.github.com/users/lkhphuc", "html_url": "https://github.com/lkhphuc", "followers_url": "https://api.github.com/users/lkhphuc/followers", "following_url": "https://api.github.com/users/lkhphuc/following{/other_user}", "gists_url": "https://api.github.com/users/lkhphuc/gists{/gist_id}", "starred_url": "https://api.github.com/users/lkhphuc/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/lkhphuc/subscriptions", "organizations_url": "https://api.github.com/users/lkhphuc/orgs", "repos_url": "https://api.github.com/users/lkhphuc/repos", "events_url": "https://api.github.com/users/lkhphuc/events{/privacy}", "received_events_url": "https://api.github.com/users/lkhphuc/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/26/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/26/timeline", "performed_via_github_app": null}